#!/usr/bin/env node
/**
 * AgriMandi Backend Fallback Config Generator
 * -----------------------------------------------------------------------------
 * Safety fallback script: if Vercel or any build system runs
 * `node scripts/build-config.js` with cwd = backend/, this script ensures
 * config.js is created without error and written to both the project root
 * and the backend directory.
 */

const fs = require('fs');
const path = require('path');

// Target paths: both root config.js and local backend config.js
const rootTargetPath = path.resolve(__dirname, '..', '..', 'config.js');
const localTargetPath = path.resolve(__dirname, '..', 'config.js');

const apiBaseUrl = (
  process.env.API_BASE_URL ||
  process.env.AGRIMANDI_API_BASE_URL ||
  'http://localhost:5000'
).trim();

const supabaseUrl = (
  process.env.SUPABASE_URL ||
  'https://your-project-id.supabase.co'
).trim();

const supabaseAnonKey = (
  process.env.SUPABASE_ANON_KEY ||
  process.env.SUPABASE_KEY ||
  process.env.SUPABASE_PUBLISHABLE_KEY ||
  'your-supabase-publishable-or-anon-key'
).trim();

const maskedKey = supabaseAnonKey.length > 10
  ? `${supabaseAnonKey.slice(0, 6)}...${supabaseAnonKey.slice(-4)}`
  : '(placeholder)';

console.log('🌱 [AgriMandi Backend Fallback] Generating config.js for deployment...');
console.log(`   - API Base URL:  ${apiBaseUrl}`);
console.log(`   - Supabase URL:  ${supabaseUrl}`);
console.log(`   - Supabase Key:  ${maskedKey}`);

const configContent = `/**
 * AgriMandi - Generated Frontend Runtime Configuration
 * Auto-generated by backend/scripts/build-config.js fallback.
 * DO NOT COMMIT THIS FILE TO VERSION CONTROL.
 */
window.AGRIMANDI_CONFIG = {
  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)}
};
`;

try {
  fs.writeFileSync(rootTargetPath, configContent, 'utf8');
  console.log(`✅ [AgriMandi] Successfully wrote root config.js to: ${rootTargetPath}`);
} catch (err) {
  console.warn(`⚠️ [AgriMandi] Could not write to root config.js:`, err.message);
}

try {
  fs.writeFileSync(localTargetPath, configContent, 'utf8');
  console.log(`✅ [AgriMandi] Successfully wrote local config.js to: ${localTargetPath}`);
} catch (err) {
  console.warn(`⚠️ [AgriMandi] Could not write to local config.js:`, err.message);
}
