#!/usr/bin/env node
/**
 * AgriMandi Frontend Config Generator
 * -----------------------------------------------------------------------------
 * Generates `config.js` in the project root from environment variables during
 * deploy time on Netlify, Vercel, or Docker.
 *
 * Usage:
 *   node scripts/build-config.js
 *
 * Environment variables:
 *   API_BASE_URL (or AGRIMANDI_API_BASE_URL): URL of Flask backend (e.g. https://agrimandi-api.onrender.com)
 *   SUPABASE_URL: Supabase Project URL (e.g. https://xyz.supabase.co)
 *   SUPABASE_ANON_KEY (or SUPABASE_KEY): Supabase Anon/Publishable API Key
 */

const fs = require('fs');
const path = require('path');

const targetPath = path.resolve(__dirname, '..', 'config.js');

const apiBaseUrl = (
  process.env.API_BASE_URL ||
  process.env.AGRIMANDI_API_BASE_URL ||
  'http://localhost:5000'
).trim();

const supabaseUrl = (
  process.env.SUPABASE_URL ||
  'https://your-project-id.supabase.co'
).trim();

const supabaseAnonKey = (
  process.env.SUPABASE_ANON_KEY ||
  process.env.SUPABASE_KEY ||
  process.env.SUPABASE_PUBLISHABLE_KEY ||
  'your-supabase-publishable-or-anon-key'
).trim();

// Mask key for safe console logging
const maskedKey = supabaseAnonKey.length > 10
  ? `${supabaseAnonKey.slice(0, 6)}...${supabaseAnonKey.slice(-4)}`
  : '(placeholder)';

console.log('🌱 [AgriMandi] Generating config.js for deployment...');
console.log(`   - API Base URL:  ${apiBaseUrl}`);
console.log(`   - Supabase URL:  ${supabaseUrl}`);
console.log(`   - Supabase Key:  ${maskedKey}`);

const configContent = `/**
 * AgriMandi - Generated Frontend Runtime Configuration
 * Auto-generated by scripts/build-config.js during build/deployment.
 * DO NOT COMMIT THIS FILE TO VERSION CONTROL.
 */
window.AGRIMANDI_CONFIG = {
  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)}
};
`;

try {
  fs.writeFileSync(targetPath, configContent, 'utf8');
  console.log(`✅ [AgriMandi] Successfully wrote config.js to: ${targetPath}`);
} catch (err) {
  console.error(`❌ [AgriMandi] Error writing config.js:`, err);
  process.exit(1);
}
